### PR TITLE
Support for no parenthesis around conditions

### PR DESCRIPTION
**Pull request by Peekmo**
Hello,

With this PR, you'll not have to set parenthesis around conditions (for, while, if, elsif)

Hope you'll like it.

Regards,
Peekmo

### CODE REVIEW

**Comment by Peekmo** [comment]
Wow, some files that I didn't touche has been change o.O Is it possible that the merge totally fucked ?
I correct it

**Comment by deathbeam** [comment]
Hmm and do you tested to compile all examples and checked if output is correct?

**Comment by deathbeam** [comment]
But it is great addition, but what about multiline statements?

**Comment by Peekmo** [comment]
Yep, all output seems correct.

For multiline statements, question is opened. Perhaps just adding parenthesis when there's multiline ? Or like ruby, using a statement like "||" or "&&" at the end of the line (but I don't really like it) 

If any better idea, I'm open ;)

**Comment by Peekmo** [comment]
I added "," to manage multiline in conditions.
You can find some example in examples/Conditions.rx

**Comment by deathbeam** [comment]
Awesome :) It still have some conflicts, so if you will fix them, I will merge this and so we can have more beautifull syntax :P

**Comment by Peekmo** [comment]
Done :)

**Comment by deathbeam** [comment]
And what will happen when I will write syntax like this?

```
if something && something.equals(5 +
  6) || something.equals(6 -
  8
```

**Comment by Peekmo** [comment]
It will fails, as in ruby. There's a syntax for multine and it must be respected.

It should be write like this
```ruby
if something && something.equals(5 +,
  6) || something.equals(6 -,
  8
```

**Comment by deathbeam** [comment]
But that will compile to this:

```
if (something && something.equals(5 +,
  6) || something.equals(6 -,
  8) {

}
```

and that is not valid syntax. Anyway, I am going to merge it because I am going to write proper method to handle any multiline things.

**Comment by Peekmo** [comment]
No, I remove the ending "," of course.

**Pull request merged**
