### PR TITLE
Add option "--raxe-only"

### PR DESCRIPTION
**Pull request by Peekmo**
With this option, the command line will only transpile in an other directory raxe files. By default, other files are copy/past to the new directory.

Moreover, it corrects a bug that I introduced when a --dest directory isn't provided.

And finally, the -t option is now optional. If you type ```haxelib run raxe``` the help is printed, but if you add ```-s``` option, it will transpile by default.

Regards,
Peekmo

### CODE REVIEW

**Comment by deathbeam** [comment]
And what about making copying only .rx files by default and adding something like --all option what will copy also other files?

**Comment by Peekmo** [comment]
I think that you'll need to copy your assets/config files to the dest directory more often because they are parts of your app. The case where you only need to get the .rx files are not so large (in my opinion)

**Comment by deathbeam** [comment]
I think most of people will have source code separated from assets. OpenFL and Luxe also works same way. And also CoffeeScript (which compiles to JS) and MoonScript (which compiles to Lua) works with that way that it copies only source code files.

**Comment by Peekmo** [comment]
Yep, so, I think that the default option should be to copy all non raxe files, because they want to have this files in their directory. If I add this "--only-raxe" option, is only for third party tools.

**Pull request merged**
